### ISSUE TITLE
update package dependencies

### ISSUE THREAD

**Issue by dylanalvarez1** [dylanalvarez1/Breakroom#12]
Trying to set this project up on a fresh machine had me run into some issues with the dependencies. Need to reevaluate it and fix accordingly.

**Comment by dylanalvarez1** [comment]
vue cli, nodemon, etc. are things that could possibly be included, or at least mentioned in the set up instructions/readme

**Comment by phillanges** [comment]
Shall we have a more thorough README still? It looks detailed enough for me.

**Comment by dylanalvarez1** [comment]
I think we're okay
